### ISSUE TITLE
live coding bremen

### ISSUE THREAD

**Issue by sbodese** [yamass/angular-livecoding#1]
Hi Yann,

kannst du bitte noch hier den code vom Dienstag committen ? Wäre klasse :-) es ist ja trainingscode und es  geht nicht um superHyperSophisticated code :-) 

Gruß

Steffen

**Comment by yamass** [comment]
Bitte schau im Branch "live-coding-jug"

https://github.com/yamass/angular-livecoding/tree/live-coding-jug

**Comment by sbodese** [comment]
Klasse, Danke!
